RedisAI/RedisAI

get_deps.sh
Output w/o this PR (MacOS):
```sh
$ sh get_deps.sh
...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 21.5M  100 21.5M    0     0  2101k      0  0:00:10  0:00:10 --:--:-- 2215k
dyld: Library not loaded: @rpath/libtensorflow.so
Referenced from: /Users/itamar/work/RedisTF/test/./a.out
Reason: image not found
get_deps.sh: line 32: 11550 Abort trap: 6           ./a.out
```
Signed-off-by: Itamar Haber <itamar@redislabs.com>
=> Fixes test failure in get_deps.sh

.dockerignore, Dockerfile, get_deps.sh
Breaks the builder to cache-able stages and also reduces the depth of clone in get_deps.sh.
LD_LIBRARY_PATH export added to /etc/profile
Signed-off-by: Itamar Haber <itamar@redislabs.com>
=> Stabilizes Dockerfile

src/err.c, src/err.h, src/redisai.c, test/basic_tests.py
This PR should address #73, #74, #75
- changed `free` to `RedisModule_Free` in ClearError
- add tests for correct and incorrect scripts
- return single-line error messages from backends to avoid the Python client hanging
=> Return single-line error in response. Free err details with RM_Free.

README.md
This information is extremely important for users especially since serialization format of some versions of PyTorch/Tensorflow might not work with other versions.
=> Dependency map between RedisAI and Backends

src/redisai.c, test/basic_tests.py
This PR solves #116.
When an error was generated inside the run processing thread a) the client wasn't unblocked b) even if it were, the error message would not have been set back to the client correctly.
This PR fixes both issues.
=> Fix handling errors when they happen in the processing thread

src/backends/torch.c, src/model.c, util/libtorch_c/torch_c.cpp, util/libtorch_c/torch_c.h
Make sure libtorch_c uses the Redis allocator for pointers that will be then freed with RedisModule_Free.
Should solve #125
=> Ensure buffers are allocated using the Redis allocator

src/redisai.h
Because we now using RedisModule_ExportSharedAPI we need to use RedisModule_GetSharedAPI in order to get the exported api in other modules.
=> change LLAPI to use RedisModule_GetSharedAPI instead of RedisModule_GetApi

src/backends/torch.c
The same thing is already done in TF and SCRIPT, but not in Torch run.
Thanks to @hhsecond for spotting this.
=> Use dynamically sized arrays to avoid leak

Dockerfile, Dockerfile-gpu
This should address the current failure in docker edge
```
6:M 14 Jun 2019 00:00:49.355 # Module /usr/lib/redis/modules/redisai.so failed to load: libgomp.so.1: cannot open shared object file: No such file or directory
```
=> Add libgomp1 as dependency in Dockerfile

Dockerfile
"apt-get install libgomp1" added for runner.
=> Fix for "failed to load: libgomp.so.1"

CMakeLists.txt, get_deps.sh, src/backends/onnxruntime.c
Addresses #179 
Release notes for ONNXRuntime 0.5 are here: https://github.com/microsoft/onnxruntime/releases/tag/v0.5.0
Notable changes:
- we don't need to write the model to a tmp file and then load, but we load the model directly from a buffer
- support for CUDA 10 (at this point we should consider switching all backends to CUDA 10, I'll open and issue for that)
- there's initial support for OpenVINO executors (which in turn can control devices like the Intel Movidius, etc, see https://docs.openvinotoolkit.org)
=> Add support for ONNXRuntime 0.5

CMakeLists.txt, Dockerfile-gpu, README.md, get_deps.sh, src/backends/onnxruntime.c, util/libtorch_c/torch_c.cpp
Addresses #181
Both PyTorch 1.2.0 and TensorFlow 1.14.0 should be backward-compatible: tests with previously exported models pass.
=> Bump dependencies to PyTorch 1.2 and TensorFlow 1.14.0

src/redisai.c
comparing with the current master branch ( ae63a99b51f5e676d5e85654dde41d63522e4752 ), changing RedisAI_Run_ThreadMain to only sleep if the last Pop was empty. 
Used [aibench creditcard-fraud testcase](https://github.com/filipecosta90/aibench)
( on OSS redis-server 5.0.5 )
Testcase | RedisAI Master OSS| RedisAI filipecosta90:perf-queuePop OSS | Difference (inferences/sec) | % improvement
-- | -- | -- | -- | --
aibench_run_inference_redisai | 888 | 16789.37 | 15901.37 | 1790.69%
```bash
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Run complete after 100000 queries with 16 workers:
All queries                                                 :
+ Inference execution latency …
```
=> [add] changed RedisAI_Run_ThreadMain to only sleep if the last Pop was empty

src/redisai.c
addresses:
#206 
after running same set of inferences of #206, RedisAI_RunSession does not report leaks:
```
38333:M 06 Sep 2019 19:00:00.875 # User requested shutdown...
38333:M 06 Sep 2019 19:00:00.879 # Redis is now ready to exit, bye bye...
--38333:0:schedule VG_(sema_down): read returned -4
==38333== 
==38333== HEAP SUMMARY:
==38333==     in use at exit: 677,270,407 bytes in 3,574,388 blocks
==38333==   total heap usage: 9,491,191 allocs, 5,916,803 frees, 3,841,565,812 bytes allocated
==38333== 
==38333== 7 bytes in 1 blocks are definitely lost in loss record 30 of 77,681
==38333==    at 0x10025EAD5: malloc (in /usr/local/Cellar/valgrind/HEAD-60ab74a/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==38333==    by 0x100019738: zmalloc (zmalloc.c:99)
==38333==    by 0x100019A85: …
```
=> [fix] free the queueItem after RedisAI_RunSession

src/backends/tensorflow.c, src/redisai.c
addresses #209 .
valgrind output after solving the unfreed error message memory. ( same test priorly pointed towards 780,780 bytes lost on RM_Strdup within `RedisModule_Strdup(TF_Message(status))` )
```
59740:M 08 Sep 2019 05:35:59.991 # User requested shutdown...
59740:M 08 Sep 2019 05:35:59.994 # Redis is now ready to exit, bye bye...
--59740:0:schedule VG_(sema_down): read returned -4
==59740== 
==59740== HEAP SUMMARY:
==59740==     in use at exit: 675,574,160 bytes in 3,638,298 blocks
==59740==   total heap usage: 11,277,530 allocs, 7,639,232 frees, 4,435,264,496 bytes allocated
==59740== 
==59740== 7 bytes in 1 blocks are definitely lost in loss record 30 of 77,668
==59740==    at 0x10025EAD5: malloc (in /usr/local/Cellar/valgrind/HEAD-60ab74a/lib/valgrind/vgpreload_memcheck-amd64-dar …
```
=> fixing memory leak on RAI_ModelCreateTF and RAI_ModelRunTF when status != TF_OK due to unfreed error message

src/redisai.c
- [fix] fixed lack of deny-oom strflag on RedisModule_CreateCommand for AI.TENSORSET, AI.MODELSET, AI.MODELRUN, AI.SCRIPTSET, AI.SCRIPTRUN
=> [fix] fixed lack of deny-oom strflag on RedisAI Commands that may use additional memory

.circleci/config.yml, src/redisai.c, src/redisai.h
The presented values were obtained with OSS Redis 5.0.5 version and RedisAI OSS ( current master )
For the used fraud detection model:
- we passed from overall 13.7K inferences per second to 18.8K
- we've reduced the overall q50 total inference time from 0.56ms to 0.41ms 
```
aibench_run_inference_redisai -workers 8 -burn-in 10 -max-queries 0 -print-interval 0 -reporting-period 1000ms -model financialNet -host redis://127.0.0.1:6379
time (ns),total inferences,instantaneous inferences/s,overall inferences/s
burn-in complete after 10 queries with 8 workers
1570011177482832000,12577,12567.20,12567.20
1570011178483315000,26216,13631.35,13099.21
1570011179483239000,40062,13846.05,13348.05
1570011180482957000,54350,14291.07,13583.69
1570011181483121000,68422,14068.83,13680.71 …
```
=> enable configuring the main thread to create a fixed number of worker threads up front per device.

.circleci/config.yml
Instead of redisfab/rmbuilder:x64-buster, trying to diagnose the following:
Docs has the old only Google analytics instead of Google tag manager line.
=> Use redislabsmodules/rmbuilder to build docs

opt/Makefile, ramp.yml, src/redisai.c, src/tensor.c, src/tensor.h, test/basic_tests.py
Adresses #84.
Replication of MODELRUN and SCRIPTRUN commands will not lead to re-executing the computation on the replicas, but just to setting the outputs on the replicas. Tests now include using replicas.
=> Replicate results of run commands instead of verbatim

.circleci/config.yml, CMakeLists.txt, Dockerfile, Dockerfile.gpu, Dockerfile.gpu-test, get_deps.sh, opt/Makefile, opt/build/libtorch/Makefile, opt/build/libtorch/repack.sh, opt/system-setup.py, src/backends/onnxruntime.c, test/basic_tests.py, test/double-panda.py, test/test_requirements.txt
- CircleCI config for running GPU jobs
- Test cases running on GPU Device
I am not using any of the existing build utilities such as system-setup.py since relying on a file inside the repo trigger rebuilding of that layer on each push which is time-consuming. We need to iterate over this and other build processes to unify the build processes and to do the packaging and release of GPU docker image etc
Also, because of the `allow growth` feature in TF, the test cases on GPU takes a lot of time now
=> Jobs on GPU

src/libtorch_c/torch_c.cpp
Since we cannot be sure that users set `requires_grad` to `False` in all their model parameters, we instantiate a `torch::NoGradGuard` to ensure no gradients are tracked, for efficiency.
=> Add NoGradGuard to libtorch execution

docs/commands.md, src/backends.c, src/backends.h, src/model.c, src/model_struct.h, src/redisai.c, src/script_struct.h, test/basic_tests.py
This PR adds a new AI.INFO command to RedisAI.
Stats on each model/script key being run are accumulated and reported periodically.
TODO items:
**UPDATE** (credit @K-Jo): avoid getting stats from all models with a single command (response potentially unbounded, it looks like a scan), but have users call `AI.INFO` with a `modelkey` as the argument. This way a) the stats will have the same lifetime as the respective models (~we can collocate stats directly in the model struct and get rid of the module-level dict~ UPDATE: we will still keep the stats in the dict to avoid accessing keyspace in the callback); b) responses will be bounded and specific for each model. Users will also be in charge of calling `RESETSTAT` on the model stats.
=> AI.INFO command

docs/commands.md, src/backends.c, src/backends.h, src/backends/onnxruntime.c, src/backends/onnxruntime.h, src/backends/tensorflow.c, src/backends/tensorflow.h, src/backends/tflite.c, src/backends/tflite.h, src/backends/torch.c, src/backends/torch.h, src/err.c, src/model.c, src/model.h, src/model_struct.h, src/redisai.c, src/redisai.h, src/tensor.c, src/tensor.h, test/basic_tests.py, test/test_data/mnist_batched.onnx, test/test_data/onnx_batch.py
Addresses #67 
[WONTFIX] Update clients
NOTE: we will update clients after this one is merged
=> Add support for batching

docs/commands.md, docs/configuring.md, mkdocs.yml
documentation PR: 
- [add] added mention to THREADS_PER_QUEUE feature. fixes #233 
- [add] splitted configuration options to a separate page
- [add] documented Intermediate tensors memory overhead when issuing AI.MODELRUN and AI.SCRIPTRUN . fixes #221 
- [add] Document the overhead of AI.TENSORGET and AI.TENSORSET with the optional arg VALUES. fixes #219
=> Updated documentation with some performance considerations

docs/performance.md, mkdocs.yml
this PR adds a performance section describing aibench. As soon as we publish the RE results we can make reference of it.
The goal of this page is to provide guidance of how to measure, what to collect,etc.
=> [add] added performance section describing aibench

docs/commands.md, src/CMakeLists.txt, src/config.h, src/model.c, src/model.h, src/model_struct.h, src/redisai.c, src/redisai.h, src/script.c, src/script.h, src/script_struct.h, src/stats.c, src/stats.h, test/tests_onnx.py, test/tests_pytorch.py, test/tests_tensorflow.py, test/tests_tflite.py
Addresses:
* #306 by adding an optional `TAG <tag>` argument to `AI.MODELSET` and `AI.SCRIPTSET`; tags are returned by `AI.MODELGET` and `AI.SCRIPTGET` and they are reported as part of `AI.INFO`
* #304 by adding a `META` or `BLOB` argument to `AI.MODELGET` and `META` or `SOURCE` argument to `AI.SCRIPTGET` to get information like backend, device, tag, with or without the actual model blob or script source
* #303 by adding two new commands `AI.MODELLIST` and `AI.SCRIPTLIST`, that return key and tag for each model or script respectively
=> Add TAG to models and revamp MODELGET

src/redisai.c, test/tests_tensorflow.py
AI.INFO originally fetches initial dictionary if MODELRUN not executed on a MODELKEY
```python
{..., 'DURATION': 0, 'SAMPLES': 0, 'CALLS': 0, ...}
```
But if MODELSET is on the same key again, INFO raises a key error
```bash
redis.exceptions.ResponseError: cannot find run info for key
```
This PR contains the modified test case for finding this
=> AI.INFO raises keyerror if MODELSET on existing key

README.md, test/test_data/graph_v2.pb, test/test_data/tf2-minimal.py, test/tests_tensorflow.py
TF2 supports freezing models, which can ben ran on TF1.15.
This PR adds a test on a MNIST-like model generated with Keras, exported through TF2 and that is ran on RedisAI.
=> Add Keras model test with TF2 model

.circleci/config.yml, test/includes.py, test/test_data/creditcardfraud.pb, test/test_requirements.txt, test/tests_common.py, test/tests_tensorflow.py
@lantiga just some extended testing for tensorset and modelrun. On tensorset it includes a multiprocess test with tensorset multiple times also in the same key ( to force eviction ).
It brings more confidence to merge this one and then #317.
=> Extended testing for tensorset and modelrun

src/CMakeLists.txt, src/backends/onnxruntime.c, src/backends/tensorflow.c, src/backends/tflite.c, src/backends/torch.c, src/err.c, src/model.c, src/redisai.c, src/redisai.h, src/script.c, src/tensor.c, src/tensor.h, src/util/queue.c, src/util/queue.h, test/tests_common.py, test/tests_onnx.py, test/tests_pytorch.py, test/tests_tensorflow.py, test/tests_tflite.py
Current WIP
- [add] simplified argument processing on RedisAI_ModelRun_RedisCommand (only 1 full-loop vs 5)
- [add] code refactoring to reduce duplicates and reduce complexity. 
- [add] enforced error reply string comparison on tests. 
- [fix] error messages consistent across commands for tensor getting, etc...
- removes usage of `RedisModule_AutoMemory(ctx)` from `RedisAI_TensorGet_RedisCommand`, `RedisAI_ModelSet_RedisCommand`, `RedisAI_ModelGet_RedisCommand`, `RedisAI_ModelDel_RedisCommand`, `RedisAI_ModelRun_RedisCommand`, `RedisAI_ScriptDel_RedisCommand`
- moves `queue` from `redisai.c` to `util/queue.c`
=> Code refactoring, consistent error messages, and RedisAI_ModelRun_RedisCommand optimizations

docs/commands.md, src/redisai.c, src/tensor.c, test/tests_common.py, test/tests_dag.py, test/tests_onnx.py, test/tests_pytorch.py, test/tests_tensorflow.py, test/tests_tflite.py
Addresses #329 
Specifically, with this PR, get methods have a uniform signature and behavior
```
TENSORGET key [META] [BLOB | VALUES]
MODELGET key [META] [BLOB]
SCRIPTGET key [META] [SOURCE]
```
If META is not specified, all methods return a raw binary BLOB, an array VALUES or a raw SOURCE string. This helps, for instance, with dumping a buffer out of a model or a tensor from the CLI.
If only META is specified, all methods return meta data in [key, val, key, val] form. This is a breaking change with respect to the previous behavior (TENSORGET would return [dtype, shape, blob] and not ['dtype', dtype, 'shape', shape, 'blob', blob]), so **THIS CHANGE WILL BREAK CLIENTS AND USER CODE**.
However, this is our last call to make the API uniform and ready for RESP3.
Other notable changes:
- keys …
=> Revamp GET methods (breaking change for clients)

README.md, docs/commands.md, docs/index.md, src/redisai.c, test/tests_dag.py, test/tests_onnx.py, test/tests_pytorch.py, test/tests_tensorflow.py, test/tests_tflite.py
While testing on of the HuggingFace models (1.3 GB), `MODELSET` was failing due to the fact that Redis strings are limited to 512 MB.
This PR gives the possibility to provide a large model in chunks, overcoming the limitation (at the cost of a transient allocation + memcpy of a large chunk of memory, but for now there are no alternatives):
```
with open(model_filename, 'rb') as f:
model = f.read()
chunk_size = 500 * 1024 * 1024
model_chunks = [model[i:i + chunk_size] for i in range(0, len(model), chunk_size)]
ret = con.execute_command('AI.MODELSET', 'm', 'TORCH', DEVICE, 'BLOB', *model_chunks)
```
Note that the API has been changed. One now has to specify `BLOB` to signal the start of chunks:
```
AI.MODELSET foo TORCH CPU BLOB ...
```
For consistency, the same was done for SCRIPTSET, with …
=> Add possibility to provide a model in chunks

docs/intro.md, mkdocs.yml
@lantiga just verified that the intro.md doc is not update to the `SOURCE` and `BLOB` added keywords. Also fixes the typo on the title of docs
try
```
cat graph.pb | docker exec -i redisai redis-cli -x \
AI.MODELSET mymodel TF CPU INPUTS a b OUTPUTS c
```
error
```
(error) ERR Insufficient arguments, missing model BLOB
```
----------------------------------------
try
```
cat myscript.py | docker exec -i redisai redis-cli -x AI.SCRIPTSET myscript CPU
```
error
```
(error) ERR Insufficient arguments, missing script SOURCE
```
=> [fix] fixed title, and intro.md examples on modelset and scriptset

docs/commands.md, src/backends/torch.c, src/libtorch_c/torch_c.cpp, src/libtorch_c/torch_c.h, src/script.c, src/script_struct.h, test/test_data/script.txt, test/tests_pytorch.py
This PR addresses #392.
A slightly different command API was chosen to keep things efficient.
We use the `$` sign to signal that `INPUTS` following that sign will be passed to the script as a list:
```
redis-cli -x AI.SCRIPTSET foo CPU SOURCE < foo.py
redis-cli AI.TENSORSET a FLOAT 1 1 VALUES 1
redis-cli AI.TENSORSET b FLOAT 1 1 VALUES 1
redis-cli AI.TENSORSET c FLOAT 1 1 VALUES 1
redis-cli AI.SCRIPTRUN foo foo INPUTS a $ b c OUTPUTS d
redis-cli AI.TENSORGET d META VALUES
```
The corresponding script will need to be type-annotated with `List[Tensor]` for the last argument
```
def foo(a : Tensor, args: List[Tensor]):
return a + torch.stack(args).sum()
```
Within the script, `args` will act as a standard Python list containing tensors.
Test has been added and docs have been updated.
=> Add support for variadic arguments to SCRIPT

src/model.c, src/model.h, src/redisai.c, src/redisai.h, src/script.c, src/script.h, src/tensor.c, src/tensor.h, test/tests_pytorch.py
This PR allows:
1. Retrieve model, script, and tensor Redis types from LLAPI so other modules can read/write AI keys 
2. Added LLAPI for variadic script input - modified the existing input and variadic input for integrity verification before adding new input. Added failure test for double variadic input.
=> Llapi updates

src/backends/onnxruntime.c, src/backends/tensorflow.c, src/backends/torch.c, test/test_data/pt-minimal-bb.pt, test/test_data/pt_minimal_bb.py, test/tests_pytorch.py
Fixes #401 
TORCH and TFLITE didn't have the issue, while ONNX and TF did.
It might also be a good idea to add a test targeting this use case (not with full Yolo to avoid including a 200+MB model, only with a tiny model simulating a 1-batch input and 3-batch output).
=> Avoid splitting outputs in batches when nbatches == 1

docs/commands.md, src/config.c, src/config.h, src/model.c, src/model_struct.h, src/redisai.c, src/script.c, src/tensor.c, src/version.h, test/tests_pytorch.py
Addresses #386 
Tests are missing, we need a strategy for downloading a large (512 MB) model from CI.
Note: this PR changes the format of RDB. Versioning is handled, ie older RDB are still loaded correctly.
=> Enable chunking for large models in AOF, RDB, replication and MODELGET

hooks/post_checkout
This explains it: https://stackoverflow.com/questions/54055666/docker-hub-and-git-submodules
=> Added hooks/post_checkout to handle dockerhub build failures

get_deps.sh
submodule pull should happen before
```shell
OS=$(python3 $HERE/opt/readies/bin/platform --os)
ARCH=$(python3 $HERE/opt/readies/bin/platform --arch)
```
These lines require `readies/bin` folder
=> Fix for get_deps.sh

src/redisai.c, test/tests_common.py
The following PR allows queering per background thread cpu usage info on `info modules` command output using [pthread_getcpuclockid](https://man7.org/linux/man-pages/man3/pthread_getcpuclockid.3.html)
Sample output when running a standalone redis-server with RedisAI and `THREAD_PER_QUEUE 10`:
```
$ redis-cli info modules
module:name=ai,ver=999999,api=1,filters=0,usedby=[],using=[],options=[]
ai_git_sha:30196294c6f240e80ff4b64aa00bc54098ec81fb
ai_threads_per_queue:10
ai_inter_op_parallelism:0
ai_intra_op_parallelism:0
ai_self_used_cpu_sys:24.336690
ai_self_used_cpu_user:71.894460
ai_children_used_cpu_sys:0.000000
ai_children_used_cpu_user:0.000000
ai_queue_CPU_bthread_#1_used_cpu_total:2.000469
ai_queue_CPU_bthread_#2_used_cpu_total:2.000419
ai_queue_CPU_bthread_#3_used_cpu_total:2.000436 …
```
=> Include per background thread cpu usage info on info modules output

src/backends/tensorflow.c, src/background_workers.c, src/dag.c, src/model.c, src/tensor.c, test/tests_sanitizer.py
This PR stems from fixing #443.
The segfault itself was due to https://github.com/RedisAI/RedisAI/blob/master/src/dag.c#L881 being `strcmp` instead of `strcasecmp`. The device check case sensitive here and only here, which lead to erratic behavior and memory corruption downstream when users specified a non-uppercase device string.
In the process, I spotted a few places where `array_append` was not reassigned, leading to potential problems.
=> Safely add to arrays + fix for #443

get_deps.sh, src/dag.c, src/run_info.c, src/tensor.c
This PR sanitizes memory access on master in view of 1.2.0
=> Valgrind fixes

docs/commands.md
AI.SCRIPTSET example has a key name of "myscript" and function name of "addtwo". AI.SCRIPTSET does not take a function name argument so the example is incorrect (and generates a syntax error). This pull request corrects the documentation.
=> AI.SCRIPTSET example doesn't work

.circleci/config.yml, CMakeLists.txt, opt/system-setup.py
This PR:
1. xenail build - Upgrade cmake and gcc version for unit tests. Run tests on every run.
2. Temporarily disabling centos7 builds
=> fix unit test build on xenail and centos7

src/run_info.c, src/run_info.h
#518 
Free the run_info internals if ref_count hits zero, without checking if it is the master copy or not.
=> Remove master field from DAG run_info

src/dag.c, tests/flow/tests_common.py
This is a temporary solution until we support non-blocking execution of these commands, since soon redis will not support client blocking through multi/lua (it will crash).
=> Return an error when trying to run MODELRUN/SCRIPTRUN/DAGRUN through multi or lua

src/redisai.c, tests/flow/tests_common.py
The following PR exposes the main thread CPU info via info modules ( linux systems only ). In that manner we will have:
- `ai_self_used_cpu_sys and ai_self_used_cpu_user`: which is the sum of resources used by all threads in the process
- `ai_children_used_cpu_sys and ai_children_used_cpu_user`: resource usage statistics for all of redis terminated child processes
-  `ai_main_thread_used_cpu_sys and ai_main_thread_used_cpu_user`: resource usage statistics for the main thread which in this case is Redis/RedisAI main thread
Sample output:
```
$ redis-cli info modules
module:name=ai,ver=999999,api=1,filters=0,usedby=[],using=[],options=[]
ai_git_sha:ffd7e8e7db02ba97d0472493d4dc626a2703eb09
ai_threads_per_queue:1
ai_inter_op_parallelism:0
ai_intra_op_parallelism:0 …
```
=> Expose Redis/RedisAI main thread cpu usage via modules info

README.md, src/DAG/dag.c, src/DAG/dag_parser.c, src/command_parser.c, src/model.c, src/modelRun_ctx.c, src/redisai.c, src/redisai.h, src/run_info.c, src/run_info.h, src/script.c, src/script.h, tests/flow/tests_llapi.py, tests/module/LLAPI.c
Support async LLAPI (part 2/3): Refactor Script run command (parsing, execution as a single DAG op, persist tensors before reply to client). Support async LLAPI, in a similar way to the new model run async LLAPI.
=> Script run refactor and llapi

src/DAG/dag.c, src/DAG/dag.h, src/DAG/dag_parser.c, src/backends/tensorflow.c, src/background_workers.c, src/command_parser.c, src/err.c, src/model.c, src/run_info.c, src/script.c, src/stats.c, src/tensor.c, src/tensor.h, src/util/queue.c
- In DAG_OP init, we allocate inkeys and outkeys arrays. When we parse model run command, we allocate inkeys and outkeys arrays as well (what causes the leaks). This PR contains a temporary fix, this will be refactor soon.
- In DAG_commandParser, the following line causes a leak:
RedisModuleString *mangled_key = RedisModule_CreateStringFromString(NULL, key); 
A call for RedisModule_FreeString was added.
- The allocation of DAG_device_ops array in RunInfo_Init is redundant (it is initialized in every shallow copy). 
- The function Tensor_DataTypeStr allocates memory on the heap to store the string that represents the tensor type, and it wasn't freed in one place. This allocation is replaced with stack allocation for char array - thus we save allocations and get rid of the leaks .
=> Fix valgrind leaks (with minor refactor)

opt/getver
this PR fixes the` getver` script to the current `version.h` format
closes #568
=> fixed getver

.circleci/config.yml
@rafie - from circle ci support:
```
Hi Dvir,
Thank you for contacting CircleCI Support.
In the build_and_package workflow, there are jobs with filters requiring the lint job. However, no filters are specified for the lint job.
By default, CircleCI will build for all branches, but won't build for any tag.
To have a build triggered when you push a tag you'll need to add the filters to the lint job too.
Let me know if this helps.
Yann - Support Engineer - CircleCI
```
=> lint on tags

src/DAG/dag_builder.c, src/DAG/dag_builder.h, src/command_parser.c, src/model.c, src/model.h, src/redisai.c, src/redisai.h, src/script.c, src/script.h, tests/module/DAG_utils.c
No need to sent RM_Key to these functions. Update the signatures in redisai.h.
=> Refactor RAI_getModel/ScriptFromKeyspace

docs/commands.md, src/backends.c, src/backends.h, src/backends/onnxruntime.c, src/backends/onnxruntime.h, src/backends/tensorflow.c, src/backends/tensorflow.h, src/backends/tflite.c, src/backends/tflite.h, src/backends/torch.c, src/backends/torch.h, src/redisai.c, src/version.h, tests/flow/tests_common.py, tests/flow/tests_onnx.py, tests/flow/tests_pytorch.py, tests/flow/tests_tensorflow.py, tests/flow/tests_tflite.py
this PR modifies `AI.INFO` arguments to optional. a call to `AI.INFO` without arguments will yields:
1. module version
2.  LLAPI version
3. RDB encoder version.
4. optional: TF version (if loaded)
5. optional onnx version (if loaded)
missing:
TFLIte version - not exported in current depdendecy structure
TORCH version - waiting for https://github.com/pytorch/pytorch/issues/44365
closes #477
=> Backend version

src/backends/onnxruntime.c, src/backends/tensorflow.c, src/serialization/RDB/decoder/current/v1/decode_v1.c, src/serialization/RDB/decoder/previous/v0/decode_v0.c, src/tensor.c, src/tensor.h, src/tensor_struct.h
this PR adds a new `len` member to `RAI_Tensor` which is lazy evaluated on `RAI_TensorLength` 
This should reduce the amount of calls to `RAI_TensorLength`
closes #495
=> tensor len member

src/serialization/AOF/rai_aof_rewrite.c
Fixes a (rightful) warning triggered on a clean build
=> Fix argument passing for tensor dtype

src/background_workers.c
this PR fixes invalid access to a queueItem after it is being removed from the queue, which sets its `prev` and `next` as NULL
closes #635
=> fix invalid access after freeing `next_item`

src/tensor.c, src/tensor.h, tests/flow/tests_withGears.py, tests/module/DAG_utils.c, tests/module/LLAPI.c
Revert to avoid breaking api with gears: return 1 if TensorGetValueAsDouble/LongLong succeeded, 0 otherwise.
Add a test with gears that checks the method that flatten tensor to list method (which use these APIs)
=> Revert TensorGetValueAsDouble/LongLong return value

src/backends/onnxruntime.c
Call ReleaseTensorTypeAndShape after running onnx model with batching.
**Waiting for the fix in minbatchsize logic before merge (currently batching is not always testes)**
=> Fix leak in running onnx with batching

src/execution/utils.c
If sharding is not enabled in enterprise shard violation cannot occur.
=> Fix sharding verification in enterprise

opt/clang-check-all.sh, opt/clang-format-all.sh, tests/flow/pt_api_test.c, tests/flow/tests_llapi.py, tests/flow/tf_api_test.c, tests/module/DAG_utils.c, tests/module/DAG_utils.h, tests/module/LLAPI.c
- Fix dead-lock in llapi tests: need to acquire and release the lock in the "on-finish" callback to ensure that "on-finish" isn't done before the main-thread has begun waiting.
- Refactor the RunResult_ctx in dag_utils to include the mutex and condition variable instead of having them global.
- Add c-lang formatting to tests files
=> LLAPI tests - fix deadlock

.circleci/config.yml, Dockerfile.gpu, Dockerfile.gpu-test, opt/pack.sh
cuda 10.2, and force remove dangling images. This is in addition to pruning after. All in an attempt to reduce the size for CI.
=> docker prune between

.circleci/config.yml
Changing CI to build all platforms, in parallel, for the platforms build. This also makes adding more in the future relatively easy, by editing the matrix variable.  We build a matrix of matrices - and run against those, in parallel.  We're also no longer using machines to build GPU docker images - but continue to for the **build_and_test_gpu** of course.
=> parallel platforms with remote dockers, matrix validation

.circleci/config.yml
This PR solves the build issue with snapshots. Specifically, we ensure that each workspace properly persists its files now, so that we can upload. In the past, we were untarring a tarball created in a previous step. This eliminates that.
=> snapshot filter fix

.circleci/config.yml
Formerly, all of our builds were serial, and during build we tagged the docker image. Once we moved to parallel we created an instability where the last build was the last item pushed to dockerhub with the same time. In reality, we only want to publish, when we are not building REDISAI_LITE. 
This PR changes the logic in circle, so that when we build without REDISAI_LITE (i.e REDISAI_LITE=0) we also publish to dockerhub.
=> publishing only when REDISAI_LITE=0

.circleci/config.yml
1. valgrind-general will now run on external PRs, but not internal unless we add the **ci-test** label.
2. gpu builds will now run on external PRs, but not internal unless we add the **ci-test** label.
3. Runs on integ branches (master and versioned) continue to run gpu builds as before
This involves moving the executing steps from the workflows to the commands section, then reusing them. As such the workflow is duplicated (with rule changes and a new name), but the commands moved.
=> circleci changes to meet the MOD-1227 goals with how ci runs

docs/commands.md, src/redisai.c
Change these commands registration so they will work on enterprise: since these commands has no arguments except from the command name, the indices mentioned in `RedisModule_CreateCommand` call must be 0.
Add a further documentation that explains that these commands will only return the models/scripts saved in the local shard.
=> Fix ai._modelscan and ai_scriptscan commands 

tests/flow/includes.py, tests/flow/tests_setup/tests.sh
When running in cluster env, if a shard is not responsive for too long, it is marked as down by the other shards. In some cases, the shard that was marked as down will consider the cluster as down before it is executing a command - and then it will fail. 
Hence, we increase this timeout (for all shards) when running valgrind on cluster
=> Fix clusterdown failure

src/execution/DAG/dag.c, src/execution/DAG/dag_op.h, src/execution/parsing/dag_parser.c, src/execution/parsing/deprecated.c, tests/flow/tests_sanitizer.py
Set status of dag tensorSet op at parse time (when it is executed). This should prevent race conditions that occur in DAG error whenever tensorset op is done in another device queue than the one where error occured.
Also, set tensorGet op status at reply time.
=> Update TensorSet and TensorGet in DAG upon execution 

ramp-light.yml, ramp-rce.yml, ramp.yml, src/redisai.c
This PR limits support for Redis 6 and above.
Affected versions: 1.2 (will be merge into 1.2.5)
Closes #831
=> support redis 6

src/backends/util.c, src/backends/util.h, src/redisai.c, tests/flow/tests_commands.py
The fifth character was not validated.
Also, for scriptstore and the deprecated modelset and scriptset, the only validation occurs in `parseDeviceStr` (which is from within the backends, after parsing stage). This PR replaces `sscanf` with `strtoll` in `parseDeviceStr`, to have safe exit in case of invalid device id string in these commands.
=> Fix device name validation in "modelstore" command

tests/flow/tests_tflite.py
this PR fixed inconsitancy in tflite test. 
it validates both outputs are the same and not nan or inf
=> avoid magic numbers in tflite

src/serialization/RDB/decoder/previous/v0/decode_v0.c, src/serialization/RDB/decoder/previous/v1/decode_v1.c, src/serialization/RDB/decoder/previous/v2/decode_v2.c, src/serialization/RDB/decoder/previous/v3/decode_v3.c, tests/flow/test_serializations.py
This PR adds to every RDB decoder version a block that enforces creation of run queue for the right device. This causes the RDB load to act like `MODELSTORE` or `SCRIPTSTORE` command.
Closes #890
=> create runqueue upon model and script loading

src/execution/DAG/dag.c, src/execution/command_parser.c, src/execution/utils.c, src/execution/utils.h, src/redisai.c
Add `getRedisVersion` util, and use it instead of RM_getServerVersion which is not supported in old versions.
=> Fix to support AI-LIGHT with redis 6.0.6

.circleci/config.yml, CMakeLists.txt
Add `-g` and `-ggdb` flags to the compiler, so we have the ability to get the debug symbols using gdb from the module's binary in production.
=> Use debug symbols

docs/commands.md, src/redisai.c, tests/flow/tests_commands.py, tests/flow/tests_pytorch.py
Extend AI.CONFIG command with AI.CONFIG GET sub-command, that allows to retrieve the current BACKENDSPATH and MODEL_CHUNK_SIZE
=> Add AI.CONFIG GET sub-command

src/execution/background_workers.c, src/execution/run_queue_info.c, tests/flow/tests_onnx.py
Update the global variable that indicates the number of RedisAI background threads from the main thread to ensure synchronization upon creating the global ONNX structure. When ONNX model is loaded via AI.MODELSTORE command for the first time, it triggers loading of ONNX backend and allocation of the global array, whose size equals to the number of background threads. Previously, the BG threads themselves where in charge of updating this counter, and there was a race condition that may lead to server crash - https://redislabs.atlassian.net/browse/MOD-3262. This PR is the fix for that issue.
=> Fix global threads count var update

get_deps.sh
As of v1.10.0 of the ONNX Runtime, Microsoft changed the string associated with the processor architecture in the name of the Mac OS X release tarball. The variable ORT_ARCH now correctly specifies x86_64 instead of x64, allowing Mac OS X users to retrieve the necessary dependency.
=> Update ORT_ARCH for Mac OS X

.circleci/config.yml
The issue is basically related to [DSU](https://circleci.com/docs/docker-layer-caching/) that caching entire `/var/lib/docker` folder to the remote volume which make it work inconsistent in cases where docker data root is being moved to a different volume (which is not being cached). So thats leaving a pointers in docker to the layers that are not existing in the new builds
=> Relocate docker data root dir

README.md
Add banner to show the current status of RedisAI to make it clear to the community that it is no longer actively maintained or supported.
=> Add 'no longer supported' banner
