src/Makefile, src/graph.c, src/graph.h, src/redisdl.c, src/tensor.c, src/tensor.h
Added Tensor.c, Tensor.h, Graph.c and Graph.h
Put basic functionalities to the correct components
=> Small refactoring stage 1

.circleci/config.yml, ramp.yml
@gkorland @itamarhaber 
I did a first stab here.  Please review
=> packaging with ramp file

docs/commands.md
Corrected AI.TENSORGET description to `get a tensor`
=> Fix AI.TENSORGET description

src/redisai.c, src/redisai.h
1. add REDISAI_LLAPI_VERSION and RedisAI_GetAPIVersion to check api version.
2. change RAI_Backend and RAI_Device from enum to define so it will be possible to use them from the redisai.h only.
=> Small api changes:

src/redisai.c, src/redisai.h, src/script.c, src/script.h
@lantiga @MeirShpilraien unsure about the Ex approach, maybe just break the "API"?
=> Script fixes and enhancement

get_deps.sh
Play nice with filesystems without owner samantics (e.g. nfs w/root_squash)
- cp --no-preserve=ownership
- tar --no-same-owner
=> Play nice with filesystems without owner samantics

src/model.c
As coded during RedisConf19
Signed-off-by: Itamar Haber <itamar@redislabs.com>
=> Model runner fixes

src/redisai.c, src/redisai.h
This PR addresses #113.
It is modeled along https://github.com/RedisLabsModules/RedisGears/pull/119
=> Use SharedAPI

src/backends/tensorflow.c, test/basic_tests.py
=> Check that names of input and output nodes is correct

src/redisai.c
=> Emit specific errors when key is empty

src/redisai.c
This PR integrates #131 by also emitting an empty key error from MODELRUN and SCRIPTRUN
=> Fix empty err msg

get_deps.sh, util/libtorch_c/torch_c.cpp
=> Add support for PyTorch 1.1

.circleci/config.yml, CMakeLists.txt, Dockerfile, Dockerfile-gpu, Makefile
Fixed RLEC problem of loading redisai.so by setting RUNPATH to /opt/redislabs/lib (via patchelf).
=> Fixed RLEC problem of loading redisai.so

examples/onnx/ScikitLearn2Production.ipynb
=> Example with onnx

src/redisai.c
Addresses #160 
/cc @MeirShpilraien
=> Fix use of key pos API, and point to first tensor key in command def

docs/commands.md, src/redisai.c, test/basic_tests.py
Addresses #158 
/cc @K-Jo @MeirShpilraien
=> Implement MODELDEL and SCRIPTDEL

README.md
=> Update incorrect path in README.md

src/redisai.c
=> Fixed error in BACKENDSPATH command

src/redisai.c
=> Return strings from MODELGET instead of integers

src/redisai.c
=> Consistency between SCRIPTSET and SCRIPTGET

Dockerfile-gpu, README.md, get_deps.sh
=> Docker GPU

README.md, docs/index.md
- including redisai-go client in documentation
=> include redisai-go client in documentation

src/redisai.c
=> Fix disconnection crash

src/redisai.c
- [add] remove the lock of global module for logging on RedisAI_RunSession ( logging is done on the callback )
**Summary Report**: Moving the error logging from the worker thread to the main thread improved or performance in around 15/20%. Not due to the logging part but due to the removal of acquiring the module global lock on every ModelRun/ScriptRun.
-------------
On client measured Overall Inferences per Second | current master (fa21096a7043e5458c47ee422dcb0e0218bb5642) | perf-runsession-lock branch |   |  
-- | -- | -- | -- | --
Test Case | RedisAI master branch + TensorFlow Library: 1.14.0 + OSS redis-server 5.0.5 ( 8 clients ) | RedisAI perf-runsession-lock branch + TensorFlow Library: 1.14.0 + OSS redis-server 5.0.5 ( 8 clients ) | Difference | % Improvement (*)
creditcard-fraud …
=> remove the lock of global module for logging on RedisAI_RunSession

Dockerfile, Dockerfile.arm, opt/build/docker/Makefile, opt/build/tensorflow/Dockerfile.arm, test/basic_tests.py
If an engine is disabled on build, do not execute its tests.
=> Selective test execution (by engine)

opt/Makefile, ramp.yml, src/config.h, src/redisai.c, test/basic_tests.py
With #157 having been merged, this PR enables AOF and runs the test suite with both RDB and AOF persistence.
TODO: activate AOF tests in CI
=> Enable AOF

.circleci/config.yml, get_deps.sh, opt/readies/bin/platform, opt/readies/paella/platform.py, opt/readies/paella/setup.py, opt/system-setup.py
* Amazon Linux support
* Added CircleCI macOS build
* Pinned pip to version 19.3.1
* osnick concept in readies/paella
=> Numerous automation changes

opt/Makefile, opt/redis_valgrind.sup
[add] add valgrind/callgrind makefile rules
=> [add] add valgrind/callgrind makefile rules

src/redisai.c
=> Check parsing result of tensor shape in tensorset to avoid oom

src/redisai.c, test/tests_tensorflow.py
Test case for testing the batching crash
=> Batching crashtest

.circleci/config.yml, docs/commands.md, src/backends.c, src/backends.h, src/backends/onnxruntime.c, src/backends/onnxruntime.h, src/backends/tensorflow.c, src/backends/tensorflow.h, src/backends/tflite.c, src/backends/tflite.h, src/backends/torch.c, src/backends/torch.h, src/err.c, src/model.c, src/model.h, src/model_struct.h, src/redisai.c, src/redisai.h, src/tensor.c, src/tensor.h, test/includes.py, test/test_data/mnist_batched.onnx, test/test_data/onnx_batch.py, test/tests_onnx.py, test/tests_pytorch.py, test/tests_tensorflow.py, test/tests_tflite.py
This PR reopens #241, which was merged and then reverted.
Issues not covered by tests emerged and need to be resolved before we merge again.
Details will follow here.
=> Add support for batching (take two)

src/backends.c, src/backends.h, src/backends/onnxruntime.c, src/backends/onnxruntime.h, src/backends/tensorflow.c, src/backends/tensorflow.h, src/backends/tflite.c, src/backends/tflite.h, src/backends/torch.c, src/backends/torch.h, src/model.c, src/model.h, src/model_struct.h, src/redisai.c
Solves with #323 for good, avoiding any shallow copying in the processing thread
=> Refactor batching mechanism, solve threading issue

src/background_workers.c, src/config.c, src/config.h, src/dag.c, src/run_info.c, src/util/dict.c, src/util/siphash.c.inc, test/tests_dag.py
This PR fixes build issues on macOS and general warnings. Also, one file was missing.
=> Fixes for macOS and in general

src/backends/onnxruntime.c, src/backends/tensorflow.c, src/backends/tflite.c, src/backends/torch.c, src/model_struct.h
Address #122 and #302 
Eventually caching could be deactivated if no RDB saving or AOF rewrite are needed.
=> Cache model blobs for faster serialization and thread-safety

src/redisai.c, test/tests_dag.py
This PR addresses #333 
DAGRUNRO is a DAGRUN command that has no support for PERSIST. This means that one can run DAGRUNRO against replicas in a master-replica configuration.
#330 will need to add this command to the docs
=> Add DAGRUNRO command

.circleci/config.yml, opt/Makefile, src/background_workers.c, src/background_workers.h, src/err.c, src/libtorch_c/torch_c.cpp, src/model.c, src/redisai.c, src/run_info.c, test/includes.py, test/tests_common.py, test/tests_dag.py, test/tests_onnx.py, test/tests_pytorch.py, test/tests_tensorflow.py, test/tests_tflite.py
- [fix] fixed PyTorch errors due to invalid memory accesses. fixes #341 
- [fix] ensure safe RAI_FreeRunInfo. fixes #340
=>  invalid memory accesses fixes and improvements

README.md, docs/quickstart.md, src/redisai.c
=> Add version check

README.md
Align with [documentation](https://oss.redislabs.com/redisai/quickstart/#building-the-module).
Signed-off-by: André Srinivasan <andre@redislabs.com>
=> Align with documentation

docs/commands.md, src/redisai.c, test/tests_onnx.py, test/tests_pytorch.py, test/tests_tensorflow.py, test/tests_tflite.py
fixes #378 and updates docs accordingly. This should not break any client (if it does then we need to adjust the clients not to be so restrictive for future changes)
=> Fixes AI.MODELGET to return INPUTS,OUTPUTS, BATCHSIZE, and MINBATCHSIZE

src/redisai.c
=> Fixed #382 AI.SCRIPTRUN results are being replicated twice

mkdocs.yml
This adds back the missing search box on the website
=> Fixes missing docs search box

docs/commands.md, src/redisai.c, test/tests_onnx.py, test/tests_pytorch.py, test/tests_tensorflow.py, test/tests_tflite.py
Cherry picks the following PRs into 1.0
- Fixed #382 AI.SCRIPTRUN results are being replicated twice https://github.com/RedisAI/RedisAI/pull/385
- Fixes AI.MODELGET to return INPUTS,OUTPUTS, BATCHSIZE, and MINBATCHSIZE https://github.com/RedisAI/RedisAI/pull/384
=> 1.0 cherry pick

README.md
Small change to the Readme to include the Typescript/Javascript client info
=> [add] Included Typescript/Javascript client info in README.md

ramp.yml
(cherry picked from commit 4b73cf7a8a223399938e6a8361d4fcadda61885b)
=> modified ramp

README.md, docs/index.md
* replace gitter with Discord
* repalce gitter with discord
(cherry picked from commit 7a30eb39f3b3ce74bf4427b9c53f0fe6163e0ca2)
=> replace gitter with Discord (#480)

get_deps.sh
=> fix_macos_get_deps

src/dag.c, src/run_info.c
=> Always free run ctx tensors through refcounting

src/backends/torch.c, src/libtorch_c/torch_c.cpp, src/libtorch_c/torch_c.h, tests/flow/tests_pytorch.py
=> Libtorch num threads

src/dag.c, src/libtorch_c/torch_c.cpp
Fixes for two memory leaks in #516
=> Valgrind fixes 1220

src/background_workers.c, src/dag.c, src/dag.h, src/model.c, src/redisai.h, src/redismodule.h, src/run_info.h, src/tensor.c, tests/flow/tests.sh, tests/flow/tests_llapi.py, tests/module/LLAPI.c, tests/module/Makefile
Added a new flow test that loads this module and tests the LLAPI (currently contains a basic check only).
The module build is done by its own make file that is triggered in tests.sh before running flow tests.
=> Create new test module that uses the LLAPI 

src/model.c, src/redisai.c, tests/flow/tests_pytorch.py
=> Fix modelscan crash due to tag being NULL

src/background_workers.c, tests/flow/tests_onnx.py
#544
Bug fix (temporary until broader refactor).
=> Fix unsafe dag release upon error

src/command_parser.c, src/model.c, src/model.h, src/redisai.c
=> fixed invalid model get reponse

opt/redis_valgrind.sup, src/DAG/dag.c, src/DAG/dag.h, src/backends.c, src/backends/tensorflow.c, src/backends/tflite.c, src/backends/torch.c, src/background_workers.c, src/command_parser.c, src/err.c, src/libtflite_c/tflite_c.cpp, src/libtflite_c/tflite_c.h, src/libtorch_c/torch_c.cpp, src/redisai.c, src/run_info.c, src/serialization/AOF/rai_aof_rewrite.c, src/serialization/RDB/decoder/current/v1/decode_v1.c, src/serialization/RDB/decoder/previous/v0/decode_v0.c, tests/flow/tests.sh, tests/flow/tests_dag.py, tests/flow/tests_pytorch.py, tests/flow/tests_tensorflow.py
=> Fix memory leaks

.circleci/config.yml
(cherry picked from commit 80bf0ebce23b854ccf070eaf938cdca6d50334ef)
=> CircleCI: support for intergration branches (#567)

src/backends/onnxruntime.c, tests/flow/tests_onnx.py
Set intra and inter op parallelism in onnx in model set
=> Support threading in onnx config 

get_deps.sh
this PR introduces `dlpack` version variable in `get_deps` script
closes #609
=> dlpack v0.3

opt/system-setup.py
CMake change to support xenial + friends.
=> cmake version change for RedisAI to rely on the build cmake

get_deps.sh, src/backends/onnxruntime.c, src/backends/tensorflow.c, src/libtflite_c/tflite_c.cpp, src/libtorch_c/torch_c.cpp, src/serialization/RDB/decoder/current/v1/decode_v1.c, src/serialization/RDB/decoder/previous/v0/decode_v0.c, src/serialization/RDB/encoder/v1/encode_v1.c, src/tensor.c
this PR upgrades to dlpack v0.4
closes #610
=> dlpack v0.4

src/tensor.c, src/tensor.h, tests/flow/includes.py, tests/flow/tests_withGears.py
Add tests to the create tensor LLAPI from gears following our support in automated testing with gears.
=> Test create tensor through gears

src/background_workers.c
this PR changes this `minbatch` logic check for not quitting the batching loop when `minbatchsize` is 0.
This will mimic the 1.0 behavior, as `minbatchsize` is checked outside the batching loop.
=> changed minbatch logic

.circleci/config.yml
moved gpu back to a docker for testing
valgrind changes to limit to personal branches
reduce valgrind runs on master and integ
=> initial ci changes

opt/build/docker/Makefile
Changing the org for pushing the docker.
=> docker org change

.circleci/config.yml
In an attempt to reduce disk storage.
=> docker prune between

.circleci/config.yml, .github/workflows/trigger-build-and-test-gpu.yaml, .github/workflows/trigger-valgrind.yaml
build only when someone is assigned to the PR
closes #734 
closes #733
=> remove the label/unlabel toggle, now on label

src/execution/parsing/dag_parser.c
Add verification that persist keys in DAG will be mapped to the right shard in enterprise cluster.
=> Validate shard for persist keys in DAG (in enterprise)

opt/build/libtorch/Dockerfile.jetson, opt/build/libtorch/Makefile
Fixed the build of pytorch so that it now works on Jetson hardware. I've pushed dependencies to s3.
=> adding build of pytorch on jetson - 1.7.0

tests/qa/release.json, tests/qa/run
Authored with @tomerhekredis to change variables being sent to opereto.
=> opereto variable changes for production run

ramp.yml, src/redisai.c, tests/flow/tests_commands.py
The command temporarily just calls scriptset until we implement it (we do it for testing DMC)
=> Add scriptstore command - temporary

.circleci/config.yml
To fix CI - using admin to merge.
=> extending the context to dockers (#780)

src/redisai.c
Remove the deprecation warning logging in MODELRUN command - for HPE.
=> Remove deprecation warning

README.md
=> README update redis version

opt/build/docker/Makefile, opt/build/docker/dockerfile.tmpl
=> adding redis to gpu images

src/execution/parsing/script_commands_parser.c, tests/flow/test_data/script.txt, tests/flow/tests_commands.py, tests/flow/tests_pytorch.py
Following @AvitalFineRedis bug:
fix script execute parsing for cases that TIMEOUT arg is given and test it
=> Fix and test script timeout

docs/index.md, docs/intro.md, docs/requirements.txt
=> Add reference to the documentation of AI-gears in docs - cherry pick

src/redis_ai_objects/tensor.c, tests/flow/tests_common.py
* fixed segmentation fault bug
in _RAI_TensorParseStringsBlob
* added test for future similar errors
(too many elements in BLOB)
=> cherry-pick String blob bug (#880)

.circleci/config.yml, tests/flow/tests_dag.py
Updated the CI config file to use redis 6.2 in valgrind tests
Fixed debug message to print test function name.
=> Slowlog impl fix

README.md, get_deps.sh, opt/build/docker/Makefile, opt/build/dockerparts/apt.yml, opt/system-setup.py, tests/flow/tests_setup/test_requirements.txt
this PR updated to pytroch 1.10.1 (1.10.1-cuda11.3 on GPU)
=> updated pytorch and cuda version

docs/requirements.txt
Upgrade patch version to fix incompatibility with updated version of jinja2 - https://github.com/mkdocs/mkdocs/issues/2799
=> Upgrade mkdock path version

README.md, docs/quickstart.md
`redisai:latest` tag is broken and `redisai:latest-cpu-x64-bionic` doesn't exist - fix docs
=> fix docs for docker latest

README.md
Updated module name and README
=> Changed name from RedisAI to redis-inference-optimization
